name: Deploy master branch

on:
  push:
    branches:
      - master
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
    branches: main

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm i -g serverless
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: deploy
        run: serverless plugin install --name serverless-domain-manager && sls deploy --stage dev --verbose
